import { chromium } from 'playwright';
const base = process.env.GT_BASE ?? 'http://localhost:4173';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
p.on('console', (m) => console.log('CONSOLE', m.type(), m.text().slice(0, 200)));
p.on('pageerror', (e) => console.log('PAGEERROR', String(e).slice(0, 300)));
await p.goto(base, { waitUntil: 'load' });
await p.waitForFunction(() => !!window.__gittimeline, null, { timeout: 30000 });
console.log('has catalog-link:', await p.getByTestId('catalog-link').count());
await p.getByTestId('catalog-link').click().catch((e) => console.log('click fail', e.message.split('\n')[0]));
await p.waitForTimeout(2500);
console.log('mode:', await p.evaluate(() => window.__gittimeline.mode));
console.log('testids:', await p.evaluate(() => [...document.querySelectorAll('[data-testid]')].map((n) => n.getAttribute('data-testid')).join(',')));
console.log('bodytext:', await p.evaluate(() => document.body.innerText.replace(/\s+/g, ' ').slice(0, 600)));
await p.screenshot({ path: process.env.GT_SHOT ?? 'gt-probe.png', fullPage: true });
await b.close();
